spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://10.10.5.64:3306/PineConeCredit?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123456
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    thymeleaf:
        mode: LEGACYHTML5
        cache: false

server:
    tomcat:
        max-threads: 10
        min-spare-threads: 10
    port: 9999

# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml